name: BiG-CZ
channels:
  - odm2
  - conda-forge
  - defaults
dependencies:
  - python=2.7
  - flake8
  - folium
  - jupyter
  - jupyter_contrib_nbextensions
  - matplotlib
  - nb_conda_kernels
  - oceans
  - odm2api
  - seaborn
  - ulmo
  - wofpy
